### ISSUE TITLE
Request better documentation on output file formats

### ISSUE THREAD

**Issue by tomgreene** [pypeit/PypeIt#1460] opened 2022-08-23 22:44 UTC
It would be helpful to users if the output file formats were documented better. The different extensions / values of the 2D spectral files seem to make sense, but it would be nice to know what all of the columns are in the extracted 1dspec, coadded, fluxed, and telluric corrected files. I can see the different values / columns using the astropy fits reader, but it is not clear what they are from their titles.

I would like to thank @jhennawi for pointing me to the pypeit code that writes the values, which has been a very helpful stopgap.

Another related documentation request is to put the flux units in the headers too (after fluxing).

**Comment by kbwestfall** [comment] 2022-08-23 22:47
Hi @tomgreene .  +1 for improving the documentation! :)  But, just to make sure, did you see this?

https://pypeit.readthedocs.io/en/release/out_spec1D.html#current-data-model

**Comment by tomgreene** [comment] 2022-08-23 22:56
Thanks @kbwestfall , I did see that but had a hard time connecting the dots between the specific output files and what data model components they contained. It is more clear now, but maybe an additional table would be helpful for more occasional users like myself (columns being the different pypeit files and rows being their specific data model value descriptors).

**Comment by jhennawi** [comment] 2022-08-24 11:09
Thanks @tomgreene for filing this request. @kbwestfall I think the issue is that OneSpec and telluric model outputs are not listed here, which is what @tomgreene was struggling with. I asked him to submit this issue as a reminder for us to document those datamodels.

**Comment by kbwestfall** [comment] 2022-10-18 21:50
Hi @tomgreene .  This is being addressed in #1488 .  Please see the under-review new format here: https://pypeit.readthedocs.io/en/doc_refactor .  Your welcome to provide any more comments here or on the PR.

**Comment by kbwestfall** [comment] 2022-10-27 00:46
Closing for now, but please do let us know if you have any more documentation requests!

**Closed as completed by kbwestfall** 2022-10-27 00:46 UTC
