### ISSUE TITLE
pypeit_show_2dspec or maybe ginga has a memory leak

### ISSUE THREAD

**Issue by eteq** [pypeit/PypeIt#1178] opened 2021-04-27 14:44 UTC
I have a workflow that involves a lot of back-to-back calls to `pypeit_show_2dspec`.  Conveniently, it will re-use the existing `ginga` window... But inconveniently, if I do this ~5-10 times, Ginga is using ~6 GB of memory.  Clearly there's *some* kind of memory leak.

It's rather unclear to me if this is a `ginga` issue or a `pypeit` issue, or a mix of the two, but I figured I'd leave this here and cc someone I know knows ginga too.

As an example invocation I've basically been doing this:

```
pypeit_show_2dspec --det 3 .../spec2d_RSSv.fits --ignore_extract_mask
```
repeatedly, on a file like this: https://www.dropbox.com/s/h2tg6wl6lnru5u1/spec2d_RSSv.fits?dl=0

(I'm not 100% sure this will reproduce since I did it with like 10 files 9 of which I've since deleted because they were temporary :shrug:)

cc @pllim (a ginga dev who was asking me about this)

**Comment by pllim** [comment] 2021-04-27 15:02
Note to self:

https://github.com/pypeit/PypeIt/blob/release/pypeit/display/display.py

https://github.com/pypeit/PypeIt/blob/release/pypeit/display/ginga_plugins.py

**Comment by jhennawi** [comment] 2021-04-27 15:30
Hi @eteq, 

Ugh, ginga issues can be pretty challenging to debug. My suggestion would be to try to reproduce the problem by stripping out as much pypeit as you can and writing a ginga script to reproduce it, and then sending that to ginga developers. The ginga folks are very responsive and fix bugs fast. All we are doing is using the RC functionality in ginga. You can write a script that executes similar commands but with no pypeit dependencies. I doubt this a pypeit issue since you are running a command line script, so the memory should clear after show2d_spec finishes (i.e. it is not a single python session). 

In my own experience, I have to restart my ginga session pretty regularly because it starts to hang. 

Joe

**Comment by pllim** [comment] 2021-04-27 15:41
I wonder if @ejeschke have any idea by looking at the implementation in https://github.com/pypeit/PypeIt/issues/1178#issuecomment-827676558 . I have not much experience with the RC portion of Ginga, but in my experience in general, besides https://github.com/ejeschke/ginga/blob/61d9791fc2803869174243510a2fabe15b22af2e/ginga/examples/configs/general.cfg#L47-L49 , which you can set as you wish, there is no other explicit control of memory use. Things can get out of hand if you create in-memory buffers (e.g., sky subtracted image array) and don't clean them up yourselves.

**Comment by jhennawi** [comment] 2021-04-27 16:06
@eteq, 

You can try adding 

display.clear_all() 

at the end. 

This will make the script useless since it will immediately clear everything after displaying it. However, it might help you diagnose whether leaving the images in ginga is the problem.

**Comment by ejeschke** [comment] 2021-04-27 19:29
(Not having looked at the implementation yet)
Couple of comments:
1) For regular paths, ginga will keep up to `numImages` in memory (and that is controlled *per-channel*) before flushing them out.  This number can be set easily by opening the `Preferences` plugin for the channel of interest, scroll down to the "General" section, open it and set the value in "Num Images".  Click the "Save Settings" button. Restart Ginga to make sure the net setting is applied to the channel ahead of loading any images.
*Note that a 0 value will disable any eviction of images from the channel* (i.e. unlimited memory). 1 or 2 is probably the value you want for large images, the default of 10 is fine for medium sized images.
2) It ought to be pretty easy to measure the memory use of Ginga with each additional image. First, be sure to set the image limit, as discussed above.  Then, using the normal `RC` method, load several paths or buffers and watch the memory use with each one.  After, hitting the `numImages` limit, the memory use should flatten out, but will always increase slightly, since Ginga will retain a thumbnail and a small record of the image in the channel to reload it if user should click on the thumb.  If buffers are sent, Ginga has no current way to reload buffers that have been ejected.

**Comment by ejeschke** [comment] 2021-04-27 19:38
For new channels created, the value of `numImages` is inherited from the settings profile of the default `Image` channel, so it would suffice to set it for that channel to have it inherited for all others. As @pllim mentioned, it can also be set in the `general.cfg` config file (but is overridden by a saved preference in the `Image` channel, if settings have been saved for that).

**Comment by ejeschke** [comment] 2021-04-27 20:15
Following my own advice, after testing with the reference viewer a bit, I'm pretty sure there is a leak in the reference viewer.  I've opened an issue, which you can see above.  I'm checking now with earlier releases.

**Comment by pllim** [comment] 2021-04-28 13:36
Update: ejeschke/ginga#948 remains inconclusive (maybe there is no leak there after all).

A hopefully easy test you can do on this side is to disable all `ginga` calls to your plotting function and see if you still see the "leak". If you do, it is probably caused by the function generating too much in-memory arrays outside of the visualization. If not, then you can maybe re-activate the `ginga` stuff one by one until you see the leak. That would help narrow things down.

**Comment by ejeschke** [comment] 2021-04-29 00:26
@eteq, @jhennawi, what version of ginga are you using?  If your interested, have a look at the issue I referenced above, but TL,DR: it doesn't look like there is any significant memory leak in ginga (at the end of the issue I tested the same RC interface method you are using (`load_np`) and it looks like ginga stays in the 600-700MB range cycling through 144 4Kx8K 16 bit buffers).  I had `numImages` set to 2.

I'll take a little longer look at your plugin, but it may just be a matter of setting this value down so that 10 large images aren't retained by default. BTW, what size images are you generating?

**Comment by jhennawi** [comment] 2021-04-29 00:31
Hi @ejeschke, 

Thanks for your help with this. I'll let @eteq answer the ginga version question. Usually with PypeIt we always are up to date, but we may need to update our requirements in the setup settings. 

Are images can be as large as 4096 by 4096 and in some cases larger. We typically have 4 tabs open with images of this size. 

What is the numImages parameter? I'm not sure where to find this or if we are using it.

**Comment by ejeschke** [comment] 2021-04-29 00:33
@jhennawi, have a look at [this comment above](https://github.com/pypeit/PypeIt/issues/1178#issuecomment-827861311).

**Comment by jhennawi** [comment] 2021-04-29 00:36
Hi @ejeschke, 

Can you look at line 515 at this link: 

https://github.com/pypeit/PypeIt/blob/release/pypeit/display/display.py

We are usually clearing ginga before running our pypeit_show_2dspec script. I think we just need to make sure that clear command is clearing everything out of ginga's memory usage.

**Comment by ejeschke** [comment] 2021-04-29 01:03
That will remove all the channels (and *should* remove all images).

If you install the Python `memory-profiler` (`pip install -U memory_profiler`) then you can pretty easily generate usage plots for ginga yourself like so:
```bash
$ mprof run ginga ...
```
Then use your ipython or jupyter session to do some loads.  Close ginga and do:
```
$ mprof plot
```
it will generate a nice plot of memory use vs. time.  I found this pretty useful.

**Comment by jhennawi** [comment] 2021-08-23 21:39
@eteq can you please update us on the status of this issue? Has it been resolved? Can we close this issue.

**Comment by kbwestfall** [comment] 2022-10-27 01:39
It's been more than a year.  Closing.

**Closed as completed by kbwestfall** 2022-10-27 01:39 UTC
