### ISSUE TITLE
Pypeyt_setup not parsing soar_goodman_red files

### ISSUE THREAD

**Issue by ntejos** [pypeit/PypeIt#1500] opened 2022-11-04 19:43 UTC
Hi,

The version of PypeIt is: 1.10.1.dev329+g4ad54968d

Issue: when running `pypeit_setup -s soar_goodman_red -r ../Raw_test/` the following error is raised: 

> Traceback (most recent call last):
>   File "/home/ntejos/anaconda3/envs/pypeit/bin/pypeit_setup", line 33, in <module>
>     sys.exit(load_entry_point('pypeit', 'console_scripts', 'pypeit_setup')())
>   File "/home/ntejos/python/PypeIt/pypeit/scripts/scriptbase.py", line 110, in entry_point
>     cls.main(cls.parse_args())
>   File "/home/ntejos/python/PypeIt/pypeit/scripts/setup.py", line 74, in main
>     ps.run(setup_only=True, sort_dir=sort_dir, write_bkg_pairs=args.background, 
>   File "/home/ntejos/python/PypeIt/pypeit/pypeitsetup.py", line 374, in run
>     self.build_fitstbl(strict=not setup_only)
>   File "/home/ntejos/python/PypeIt/pypeit/pypeitsetup.py", line 265, in build_fitstbl
>     self.fitstbl = PypeItMetaData(self.spectrograph, par=self.par, 
>   File "/home/ntejos/python/PypeIt/pypeit/metadata.py", line 115, in __init__
>     else self._build(files, strict=strict, 
>   File "/home/ntejos/python/PypeIt/pypeit/metadata.py", line 203, in _build
>     value = self.spectrograph.get_meta_value(headarr, meta_key, 
>   File "/home/ntejos/python/PypeIt/pypeit/spectrographs/spectrograph.py", line 1198, in get_meta_value
>     value = headarr[self.meta[meta_key]['ext']][self.meta[meta_key]['card']]
> IndexError: list index out of range

There are 3 SOAR files inside ``../Raw_test/`` which can be (temporarily) found here: https://drive.google.com/drive/folders/1s5cggkfS9fMKrrInkDgUxO_OiaEv5RmD?usp=sharing for reference.

This suggests that is a parsing issue with the file headers, but not sure. Happy to provide further information if needed. Thanks in advance for any help on this!

**Comment by kbwestfall** [comment] 2022-11-07 16:10
I took a quick look at this.  The issue is that the format of the files are different from what PypeIt expects.  The files we have in our dev-suite are all `*.fz` files that have two extensions.  So PypeIt pulls header data from the 2nd extension.  Your files only have one extension, so the code barfs when it tries to access the header of the non-existent 2nd extension.  Do you have `*.fz` versions of the files that have two extensions?

**Comment by ntejos** [comment] 2022-11-07 16:41
I see, thanks for looking at this. I do not have the corresponding `.fz` files, I retrieved these SOAR files via direct communication with the observer.

**Comment by kbwestfall** [comment] 2022-11-07 16:44
Hmm... That sounds like something PypeIt should allow!  I think @profxj was the one that wrote the SOAR spectrograph class, so we should check with him about why the files are different.

**Comment by rcooke-ast** [comment] 2022-11-07 16:55
FYI - I ran into this issue too with SOAR Goodman data... I'm pretty sure it can be resolved by downloading the .fz files (which is the default "preferred" option by the SOAR archive). If there's no way for you to get the SOAR files in .fz format, check out this PR, which will help you to modify your version of PypeIt to reduce your data:

[https://github.com/pypeit/PypeIt/pull/1303](https://github.com/pypeit/PypeIt/pull/1303)

**Comment by ntejos** [comment] 2022-11-07 19:25
Thanks @rcooke-ast - If I compress using rice, Pypeit seems to recognize the files and work properly. We can close this issue, but it would be good to add a warning somewhere in the code for cases when the files are not `.fz` for SOAR.

**Comment by rcooke-ast** [comment] 2022-11-07 19:38
No problems! It's not so straightforward to do that in the code at the moment, but maybe it would help to add this in a general way... will think about this some more before closing...

**Comment by rcooke-ast** [comment] 2022-11-07 20:52
OK @ntejos - I have added a hook for this. Addressed by PR #1502... closing

**Closed as completed by rcooke-ast** 2022-11-07 20:52 UTC
