### ISSUE TITLE
Crashing out of bspline_profile

### ISSUE THREAD

**Issue by profxj** [pypeit/PypeIt#683] opened 2019-05-13 21:24 UTC
Fails on DEIMOS masks which are well traced and appear to have good wavelength solutions.

I've put the files in the 1200G_Cooper folder on the Dev Suite drive.

Here is the trace:

[WARNING] :: pydl.py 874 cholesky_band() - NaN found in cholesky_band.
[INFO]    :: utils.py 481 bspline_profile() -                                25    ---    ---    ---    ---
[WARNING] :: pydl.py 874 cholesky_band() - NaN found in cholesky_band.
[INFO]    :: utils.py 481 bspline_profile() -                                26    ---    ---    ---    ---
[INFO]    :: utils.py 493 bspline_profile() - ***************************************************************************************************
[INFO]    :: utils.py 496 bspline_profile() - Final fit after 26 iterations: reduced_chi =    0.000, rejected =       0, relative_factor =   1.00
Traceback (most recent call last):
  File "/home/xavier/.pyenv/versions/anaconda3-5.2.0/bin/run_pypeit", line 7, in <module>
    exec(compile(f.read(), __file__, 'exec'))
  File "/data/Projects/Python/PypeIt/bin/run_pypeit", line 17, in <module>
    rtval = run_pypeit.main(args)
  File "/data/Projects/Python/PypeIt/pypeit/scripts/run_pypeit.py", line 95, in main
    pypeIt.reduce_all()
  File "/data/Projects/Python/PypeIt/pypeit/pypeit.py", line 300, in reduce_all
    sci_dict = self.reduce_exposure(frames, bg_frames=bg_frames, std_outfile=std_outfile)
  File "/data/Projects/Python/PypeIt/pypeit/pypeit.py", line 404, in reduce_exposure
    self.caliBrate.run_the_steps()
  File "/data/Projects/Python/PypeIt/pypeit/calibrations.py", line 836, in run_the_steps
    getattr(self, 'get_{:s}'.format(step))()
  File "/data/Projects/Python/PypeIt/pypeit/calibrations.py", line 510, in get_flats
    self.mspixelflat, self.msillumflat = self.flatField.run(show=self.show, maskslits=self.tslits_dict['maskslits'])
  File "/data/Projects/Python/PypeIt/pypeit/flatfield.py", line 244, in run
    debug=debug)
  File "/data/Projects/Python/PypeIt/pypeit/core/flat.py", line 303, in fit_flat
    bsp_set = pydl.bspline(ximg_fit,nord=4, bkspace=ximg_bsp)
  File "/data/Projects/Python/PypeIt/pypeit/core/pydl.py", line 265, in __init__
    startx = x.min()
  File "/home/xavier/.pyenv/versions/anaconda3-5.2.0/lib/python3.6/site-packages/numpy/core/_methods.py", line 32, in _amin
    return umr_minimum(a, axis, None, out, keepdims, initial)
ValueError: zero-size array to reduction operation minimum which has no identity

**Comment by profxj** [comment] 2019-05-13 21:25
I believe I hit a similar crash on LRISb recently.  Will confirm..

**Comment by jhennawi** [comment] 2019-05-13 21:35
Hi @profxj go ahead and add these files to the Google drive if you have not already with associated PypeIt file.

**Comment by profxj** [comment] 2019-05-14 22:45
Same crash on `detnum=7`   @jhennawi

**Comment by profxj** [comment] 2019-06-02 15:22
@jhennawi -- This is now pervasive.
Am crashing out of extracting a standard
star for MagE.  Am going to share those files
with you privately (they are of an FRB).

**Comment by WeichenStars** [comment] 2019-09-13 20:32
Hi everyone,
     Thanks for this amazing new pipeline. I played around with my DEIMOS data and got the same error message.
 
    I think what happened is that the __init__ function of class bspline crashes when receiving an empty numpy array as parameter x (I guess x represents the 2d flux map of a slit?). Source code is located starting from line 227 of core/pydl.py.  

   Line 248 in this pydl.py did handle the case that x is None, but not the case that x can be an empty array.

   Regarding the error message:
    line 303, in fit_flat
    bsp_set = pydl.bspline(ximg_fit,nord=4, bkspace=ximg_bsp)

   I think it is ximg_fit that is the empty numpy array that feeds into __init__  in bspline.

   My current workaround solution is to wrap the slit-by-slit flat fielding steps of flatfield.py into a try-catch code block. It simply avoids this bug killing the whole working flow by skipping the slit that raised this kind of error.

   Specifically, I replace line 224-255 in flatfield.py by:

           try:
                pixelflat, illumflat, flat_model, tilts_out, thismask_out, slit_left_out, slit_righ_out = \
                    flat.fit_flat(self.rawflatimg, this_tilts_dict, self.tslits_dict, slit,
                                inmask=inmask,
                                nonlinear_counts=nonlinear_counts,
                                spec_samp_fine=self.flatpar['spec_samp_fine'], 
                                spec_samp_coarse=self.flatpar['spec_samp_coarse'],
                                spat_samp=self.flatpar['spat_samp'], tweak_slits=self.flatpar['tweak_slits'],
                                tweak_slits_thresh=self.flatpar['tweak_slits_thresh'],
                                tweak_slits_maxfrac=self.flatpar['tweak_slits_maxfrac'],debug=debug)
                self.mspixelflat[thismask_out] = pixelflat[thismask_out]
                self.msillumflat[thismask_out] = illumflat[thismask_out]
                self.flat_model[thismask_out] = flat_model[thismask_out]
                # Did we tweak slit boundaries? If so, update the tslits_dict and the tilts_dict
                if self.flatpar['tweak_slits']:
                    self.tslits_dict['slit_left'][:, slit] = slit_left_out
                    self.tslits_dict['slit_righ'][:, slit] = slit_righ_out
                    self.tslits_dict['slit_left_tweak'][:, slit] = slit_left_out
                    self.tslits_dict['slit_righ_tweak'][:, slit] = slit_righ_out
                    final_tilts[thismask_out] = tilts_out[thismask_out]

                # If we tweaked the slits update the tilts_dict
                if self.flatpar['tweak_slits']:
                    self.tilts_dict['tilts'] = final_tilts

                if show:
                    # Global skysub is the first step in a new extraction so clear the channels here
                    self.show(slits=True, wcs_match = True)
            
            except Exception as e:
                
                print('[Warning]: ', e)
                msgs.warn('Flat field construction: This slit is skipped (flat = all 1\'s) coz fit_flat crashed!')
                continue

       Hope this helps.

Best,
Weichen

**Comment by jhennawi** [comment] 2019-09-13 23:32
Hi @WeichenStars, 

Thanks for the kind words. While I agree that a try except block is a possibility here, the problem is the user does then not know that the flat field did not work. For that reason I've left this crash in there. 

The crash has been fixed in the develop branch, at least the code prints out a warning explaining why it crashes. I'm not sure if it is in master yet. Most crashes here are caused by the fact that the flats are saturated. So the correct solution is to increase the saturation value parameter. Actually the correct solution would be for the user to use non-saturated flats. 

I'm not sure what the best compromise is. I don't like skipping the slit without letting the user now that they should aim for short flat exposure times. On the other hand, I understand it can be annoying to have the reduction crash on account of one bad slit. Probably we need a step that checks the flat count levels and prints out a less cryptic error message, with some instructions about how to modify the pypeit file if they want to continue.

**Comment by WeichenStars** [comment] 2019-09-15 18:53
Thanks for the reply! I fully agree that users should be notified and allowed to track down the errors when they happened. Really looking forward to future completion of this nice pipeline.

**Closed** 2019-09-24 20:46 UTC
